// js/bible-data.js

export const BIBLE_DATA = [
    // --- VELHO TESTAMENTO ---
    { id: 1,  nome: "Génesis", caps: 50, abrev: "Gén" },
    { id: 2,  nome: "Êxodo", caps: 40, abrev: "Êx" },
    { id: 3,  nome: "Levítico", caps: 27, abrev: "Lev" },
    { id: 4,  nome: "Números", caps: 36, abrev: "Núm" },
    { id: 5,  nome: "Deuteronómio", caps: 34, abrev: "Deut" },
    { id: 6,  nome: "Josué", caps: 24, abrev: "Jos" },
    { id: 7,  nome: "Juízes", caps: 21, abrev: "Juí" },
    { id: 8,  nome: "Rute", caps: 4, abrev: "Rute" },
    { id: 9,  nome: "1 Samuel", caps: 31, abrev: "1 Sam" },
    { id: 10, nome: "2 Samuel", caps: 24, abrev: "2 Sam" },
    { id: 11, nome: "1 Reis", caps: 22, abrev: "1 Reis" },
    { id: 12, nome: "2 Reis", caps: 25, abrev: "2 Reis" },
    { id: 13, nome: "1 Crónicas", caps: 29, abrev: "1 Crón" },
    { id: 14, nome: "2 Crónicas", caps: 36, abrev: "2 Crón" },
    { id: 15, nome: "Esdras", caps: 10, abrev: "Esd" },
    { id: 16, nome: "Neemias", caps: 13, abrev: "Nee" },
    { id: 17, nome: "Ester", caps: 10, abrev: "Est" },
    { id: 18, nome: "Jó", caps: 42, abrev: "Jó" },
    { id: 19, nome: "Salmos", caps: 150, abrev: "Sal" },
    { id: 20, nome: "Provérbios", caps: 31, abrev: "Prov" },
    { id: 21, nome: "Eclesiastes", caps: 12, abrev: "Ecl" },
    { id: 22, nome: "Cântico de Salomão", caps: 8, abrev: "Cân" },
    { id: 23, nome: "Isaías", caps: 66, abrev: "Isa" },
    { id: 24, nome: "Jeremias", caps: 52, abrev: "Jer" },
    { id: 25, nome: "Lamentações", caps: 5, abrev: "Lam" },
    { id: 26, nome: "Ezequiel", caps: 48, abrev: "Eze" },
    { id: 27, nome: "Daniel", caps: 12, abrev: "Dan" },
    { id: 28, nome: "Oseias", caps: 14, abrev: "Ose" },
    { id: 29, nome: "Joel", caps: 3, abrev: "Joel" },
    { id: 30, nome: "Amós", caps: 9, abrev: "Amós" },
    { id: 31, nome: "Obadias", caps: 1, abrev: "Oba" },
    { id: 32, nome: "Jonas", caps: 4, abrev: "Jon" },
    { id: 33, nome: "Miqueias", caps: 7, abrev: "Miq" },
    { id: 34, nome: "Naum", caps: 3, abrev: "Naum" },
    { id: 35, nome: "Habacuque", caps: 3, abrev: "Hab" },
    { id: 36, nome: "Sofonias", caps: 3, abrev: "Sof" },
    { id: 37, nome: "Ageu", caps: 2, abrev: "Ageu" },
    { id: 38, nome: "Zacarias", caps: 14, abrev: "Zac" },
    { id: 39, nome: "Malaquias", caps: 4, abrev: "Mal" },

    // --- NOVO TESTAMENTO ---
    { id: 40, nome: "Mateus", caps: 28, abrev: "Mat" },
    { id: 41, nome: "Marcos", caps: 16, abrev: "Mar" },
    { id: 42, nome: "Lucas", caps: 24, abrev: "Luc" },
    { id: 43, nome: "João", caps: 21, abrev: "João" },
    { id: 44, nome: "Atos", caps: 28, abrev: "Atos" },
    { id: 45, nome: "Romanos", caps: 16, abrev: "Rom" },
    { id: 46, nome: "1 Coríntios", caps: 16, abrev: "1 Cor" },
    { id: 47, nome: "2 Coríntios", caps: 13, abrev: "2 Cor" },
    { id: 48, nome: "Gálatas", caps: 6, abrev: "Gál" },
    { id: 49, nome: "Efésios", caps: 6, abrev: "Efé" },
    { id: 50, nome: "Filipenses", caps: 4, abrev: "Fil" },
    { id: 51, nome: "Colossenses", caps: 4, abrev: "Col" },
    { id: 52, nome: "1 Tessalonicenses", caps: 5, abrev: "1 Tes" },
    { id: 53, nome: "2 Tessalonicenses", caps: 3, abrev: "2 Tes" },
    { id: 54, nome: "1 Timóteo", caps: 6, abrev: "1 Tim" },
    { id: 55, nome: "2 Timóteo", caps: 4, abrev: "2 Tim" },
    { id: 56, nome: "Tito", caps: 3, abrev: "Tito" },
    { id: 57, nome: "Filémom", caps: 1, abrev: "Flm" },
    { id: 58, nome: "Hebreus", caps: 13, abrev: "Heb" },
    { id: 59, nome: "Tiago", caps: 5, abrev: "Tia" },
    { id: 60, nome: "1 Pedro", caps: 5, abrev: "1 Ped" },
    { id: 61, nome: "2 Pedro", caps: 3, abrev: "2 Ped" },
    { id: 62, nome: "1 João", caps: 5, abrev: "1 João" },
    { id: 63, nome: "2 João", caps: 1, abrev: "2 João" },
    { id: 64, nome: "3 João", caps: 1, abrev: "3 João" },
    { id: 65, nome: "Judas", caps: 1, abrev: "Jud" },
    { id: 66, nome: "Apocalipse", caps: 22, abrev: "Apo" }
];

// Array simples apenas com os nomes (para compatibilidade com o código antigo)
export const BIBLICAL_BOOKS = BIBLE_DATA.map(book => book.nome);
